[package]
name = "sntkc"
version = "0.0.0"
edition = "2021"

[dependencies]
sntk_core = { path = "../sntk_core" }
sntk_ir = { path = "../sntk_ir" }
sntk_compiler = { path = "../sntk_compiler" }
clap = { version = "4.1.4", features = ["derive"] }
