[package]
name = "sigc"
version = "0.0.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
analyzer = { path = "../analyzer" }
clap = { version = "4.1.4", features = ["derive"] }
lazy_static = "1.4.0"

[build-dependencies]
serde_json = "1.0.64"
